#!/bin/bash
echo "Upload des blocks"
storyblok push-components --space $1 components.306047.json
echo "Upload des pages"
curl "https://mapi.storyblok.com/v1/spaces/$1/stories/" -X POST -H "Content-Type: application/json" -H "Authorization: dfXFbjQSjVWeg6cFphjRMwtt-133759-Pi795XW1CL77EYvQP5md" -d @./templates/starter/liberal/home.json
curl "https://mapi.storyblok.com/v1/spaces/$1/stories/" -X POST -H "Content-Type: application/json" -H "Authorization: dfXFbjQSjVWeg6cFphjRMwtt-133759-Pi795XW1CL77EYvQP5md" -d @./templates/starter/liberal/cgu.json
curl "https://mapi.storyblok.com/v1/spaces/$1/stories/" -X POST -H "Content-Type: application/json" -H "Authorization: dfXFbjQSjVWeg6cFphjRMwtt-133759-Pi795XW1CL77EYvQP5md" -d @./templates/starter/liberal/settings.json
